### PR TITLE
Improve ENV

### PR DESCRIPTION
**Pull request by timkurvers**
This adds a sample with all environment variables and attempts avoiding ambiguity.

### CODE REVIEW

**Comment by jgorset** [comment]
:+1:

**Comment by zenangst** [comment]
@jgorset sure

**Comment by timkurvers** [comment]
ok...

**Comment by jgorset** [comment]
:+1: @zenangst

**Comment by timkurvers** [comment]
@jgorset: Shouldn't you be in Denmark?

**Comment by jgorset** [comment]
@timkurvers: I am in Denmark.

**Comment by timkurvers** [comment]
BUT, HOW!?

**Comment by jgorset** [comment]
It's the internet, @timkurvers.

**Comment by sindrenm** [comment]
Isn't Denmark to flat for the Internet?

**Comment by timkurvers** [comment]
Jaw Drop

**Comment by zenangst** [comment]
the-big-lebowski-reunion-animated-gifs-15

**Pull request merged**
