### PR TITLE
Fix weird rendered list

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by sindrenm** [comment]
Weren't those supposed to be there? Looked grouped to me.

**Comment by sindrenm** [comment]
Although I admit the grouping is kinda weird. xD

**Comment by timkurvers** [comment]
Yeah, they are supposed to be there, but it seems to be a GitHub/Markdown rendering bug.

@3lvis could you add back that final newline you removed? It marks the beginning of a new section with a double newline.

**Comment by 3lvis** [comment]
There are better ways to group than newlines anyway

**Comment by timkurvers** [comment]
They should kind of be grouped alphabetically now, but #yolo.

**Comment by timkurvers** [comment]
Thanks! :cake:

**Pull request merged**
